# Boards configuration
# This configuration is dynamic

refresh_rate: 2.0
default: h
width: 8

# Change this to whatever you like,
# Especially if you don't trust your
# provider
token: blob
port: 8808

styles:
  default: &style-default
    background: '#1e1d24'
    foreground: '#fff'
    secondary: '#2b2a33'
    tiercary: '#6c6c75'
    active: '#4e4d55'
  
  oled: &style-oled
    background: '#000'
    foreground: '#fff'
    secondary: '#141414'
    tiercary: '#7b7b7b'
    active: '#1d1d1d'
  
  light: &style-light
    background: '#8a8a8a'
    foreground: '#404040'
    secondary: '#8f8f8f'
    tiercary: '#575757'
    active: '#707070'
  
  bdv: &style-bdv
    background: '#18181a'
    foreground: '#f8f8f2'
    secondary: '#232327'
    tiercary: '#6c6c75'
    active: '#18181a'
    gradient: 'linear-gradient(-65deg, #fd575a, #fc8151, #f9b931, #f9b931)'

# CSS variables to override
css: *style-default

boards:
  h:
    name: Main

    modules:
      - name: date
        geometry: 4x2,1+1
      - name: home/buttons/sleep
        geometry: 2x2,5+1
      - name: home/dot
        geometry: 2x2,7+1
      
      - name: home/stats/cpu
        geometry: 2x2,1+3
      - name: home/stats/ram
        geometry: 2x2,3+3
      - name: home/stats/gpu
        geometry: 2x2,5+3
      - name: home/stats/net
        geometry: 2x2,7+3
      
      - name: home/stats/temp
        geometry: 2x4,1+5
      - name: home/face
        geometry: 4x4,3+5
      - name: home/mouse
        geometry: 2x2,7+5
      - name: home/keyboard
        geometry: 2x2,7+7
      
      - name: home/buttons/pause
        geometry: 2x2,1+9
      - name: home/buttons/like
        geometry: 2x2,3+9
      - name: home/buttons/mute
        geometry: 2x2,5+9
      - name: home/buttons/deafen
        geometry: 2x2,7+9
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/proc
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

  t:
    name: Timer

    modules:
      - name: date
        geometry: 8x2,1+1
      
      - name: timer/timer/display
        geometry: 4x4,5+3
      - name: timer/timer/header
        geometry: 4x1,1+3
      - name: timer/timer/bubble
        geometry: 2x1,1+4
        data: 30
      - name: timer/timer/bubble
        geometry: 2x1,3+4
        data: 60
      - name: timer/timer/bubble
        geometry: 2x1,1+5
        data: 600
      - name: timer/timer/bubble
        geometry: 2x1,3+5
        data: 1800
      - name: timer/timer/bubble
        geometry: 2x1,1+6
        data: 3600
      - name: timer/timer/bubble
        geometry: 2x1,3+6
        data: 7200

      - name: timer/crono/display
        geometry: 4x4,1+7
      - name: timer/crono/header
        geometry: 4x4,5+7
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/proc
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11
  
  p:
    name: Processes

    modules:
      - name: proc/display
        geometry: 8x8,1+1
      - name: proc/footer
        geometry: 8x2,1+9

      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/proc
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

  r:
    name: Russian

    modules:
      - name: keyboard/header
        geometry: 6x2,1+1
      - name: keyboard/russian
        geometry: 2x2,7+1
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/proc
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

  l:
    name: Lock

    modules:
      # - name: date
      #   geometry: 4x2,3+3
      - name: lock/face
        geometry: 4x4,3+5
      - name: lock/unlock
        geometry: 4x1,3+9

# EOF