# Boards configuration
# This configuration is dynamic

refresh_rate: 2.0
default: h
width: 8

# Change this to whatever you like,
# Especially if you don't trust your
# provider
token: blob

styles:
  default: &style-default
    background: '#1e1d24'
    foreground: '#fff'
    secondary: '#2b2a33'
    tiercary: '#6c6c75'
    active: '#4e4d55'
  
  oled: &style-oled
    background: '#000'
    foreground: '#fff'
    secondary: '#141414'
    tiercary: '#7b7b7b'
    active: '#1d1d1d'
  
  light: &style-light
    background: '#8a8a8a'
    foreground: '#404040'
    secondary: '#8f8f8f'
    tiercary: '#575757'
    active: '#707070'
  
  bdv: &style-bdv
    background: '#18181a'
    foreground: '#f8f8f2'
    secondary: '#232327'
    tiercary: '#6c6c75'
    active: '#18181a'
    gradient: 'linear-gradient(-65deg, #fd575a, #fc8151, #f9b931, #f9b931)'

# CSS variables to override
css: *style-light

boards:
  h:
    name: Main

    modules:
      - name: display/date
        geometry: 4x2,1+1
      - name: button/sleep
        geometry: 2x2,5+1
      - name: display/dot
        geometry: 2x2,7+1
      
      - name: stat/cpu
        geometry: 2x2,1+3
      - name: stat/ram
        geometry: 2x2,3+3
      - name: stat/gpu
        geometry: 2x2,5+3
      - name: stat/net
        geometry: 2x2,7+3
      
      - name: stat/temp
        geometry: 2x4,1+5
      - name: display/face
        geometry: 4x4,3+5
      - name: mouse
        geometry: 2x2,7+5
      - name: keyboard
        geometry: 2x2,7+7
      
      - name: button/pause
        geometry: 2x2,1+9
      - name: button/like
        geometry: 2x2,3+9
      - name: button/ds-mute
        geometry: 2x2,5+9
      - name: button/ds-deafen
        geometry: 2x2,7+9
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/mail
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

  t:
    name: Timer

    modules:
      - name: display/date
        geometry: 8x2,1+1
      
      - name: timer/display
        geometry: 4x4,5+3
      - name: timer/header
        geometry: 4x1,1+3
      - name: timer/bubble
        geometry: 2x1,1+4
        data: 30
      - name: timer/bubble
        geometry: 2x1,3+4
        data: 60
      - name: timer/bubble
        geometry: 2x1,1+5
        data: 600
      - name: timer/bubble
        geometry: 2x1,3+5
        data: 1800
      - name: timer/bubble
        geometry: 2x1,1+6
        data: 3600
      - name: timer/bubble
        geometry: 2x1,3+6
        data: 7200

      - name: crono/display
        geometry: 4x4,1+7
      - name: crono/header
        geometry: 4x4,5+7
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/mail
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11
  
  m:
    name: Mails

    modules:
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/mail
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

  r:
    name: Russian

    modules:
      - name: ru-header
        geometry: 6x2,1+1
      - name: ru-keyboard
        geometry: 2x2,7+1
      - name: link/home
        geometry: 2x2,1+11
      - name: link/timer
        geometry: 2x2,3+11
      - name: link/mail
        geometry: 2x2,5+11
      - name: link/russian
        geometry: 2x2,7+11

# EOF