# Boards configuration

refresh_rate: 2.0
default: main
width: 8

whitelist:
  - 127.0.0.1
  - 192.168.1.41
  - 192.168.1.43
  - 192.168.1.6

boards:
  main:
    name: Main

    modules:
      - name: display/date
        geometry: 4x2,1+1
      - name: button/sleep
        geometry: 2x2,5+1
      - name: display/dot
        geometry: 2x2,7+1
      
      - name: stat/cpu
        geometry: 2x2,1+3
      - name: stat/ram
        geometry: 2x2,3+3
      - name: stat/gpu
        geometry: 2x2,5+3
      - name: stat/net
        geometry: 2x2,7+3
      
      - name: stat/disks
        geometry: 2x4,1+5
      - name: display/face
        geometry: 4x4,3+5
      - name: mouse
        geometry: 2x2,7+5
      - name: keyboard
        geometry: 2x2,7+7
      
      - name: button/pause
        geometry: 2x2,1+9
      - name: button/like
        geometry: 2x2,3+9
      - name: button/ds-mute
        geometry: 2x2,5+9
      - name: button/ds-deafen
        geometry: 2x2,7+9
      
      - name: link/home
        geometry: 2x2,1+11
      - name: link/disks
        geometry: 2x2,3+11
      - name: link/russian
        geometry: 2x2,7+11

  disks:
    name: Disks

    modules:
      - name: link/home
        geometry: 2x2,1+11
      - name: link/disks
        geometry: 2x2,3+11
      - name: link/russian
        geometry: 2x2,7+11
  
  russian:
    name: Russian

    modules:

      - name: ru-header
        geometry: 6x2,1+1
      - name: ru-keyboard
        geometry: 2x2,7+1
      - name: link/home
        geometry: 2x2,1+11
      - name: link/disks
        geometry: 2x2,3+11
      - name: link/russian
        geometry: 2x2,7+11

# EOF